### ISSUE TITLE
Keywords missing after 2.0 deployment

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#416]
Keywords no longer display, these were visible on test previously.  Might be related to reindexing that was done.

**Comment by dolsysmith** [comment]
Here's a plan for troubleshooting:

- [x] Re-migrate the data from gwfedora-prod2 to the prod instance on AWS, and apply the updated schema for GWSS 2.0.
- [ ] Create a new test instance and re-migrate the data.
- [ ] Reindex a single work on gwfedora-prod2: does the same problem happen there? 
- [ ] Dig into the `update_index` code (method on an `ActiveFedora` object) to trace the process.

I'll also ask for suggestions on the Samvera Slack.

**Comment by dolsysmith** [comment]
Bug was due to a breaking change in Hyrax 3.0. After running a migration task, keywords now appear properly in prod:
> rake hyrax:migrate:migrate_keyword_predicate

However, running the reindex task does **not** fix the related issue of empty keyword fields on certain ETD's. (That stands to reason: we thought the reindex task fixed the issue because it actually deleted **all** keywords when run against the unmigrated Fedora database.) 

<img width="960" alt="Screenshot 2023-10-24 at 9 02 37 AM" src="https://github.com/gwu-libraries/scholarspace-hyrax/assets/22801679/d1632743-8c22-4ad6-90b4-ccdd883da833">

To fix this issue, we'll need to write a task to find all works with an empty string in the`keyword` field and correct them. The following logic works on test:
```
work.keyword = []
work.save
```

**Comment by dolsysmith** [comment]
Rake task has been tested and just needs to be applied to prod.

**Comment by kerchner** [comment]
@dolsysmith I assume this can be closed, but wanted to double check.

**Comment by dolsysmith** [comment]
Yes, thank you!
