### ISSUE TITLE
Behavior of sitemap job

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/scholarspace-hyrax#461]
The sitemap task is correctly added to the crontab when starting a new Sidekiq container, but on prod/test it doesn't seem to create the initial sitemap.xml. By inspecting `/var/log/syslog` in the Sidekiq container, I can see that the job has run on schedule, but there is no sitemap. Running the Rake task manually _does_ create the sitemap. Because this task seems to produce no logs, and because Sidekiq does not keep a record of completed jobs, I can't tell whether the cron job failed and if so, why. 

On my dev environment, by changing the frequency (in `config/sitemap.rb`)  from monthly to daily, I was able to see that the cron job did produce updated sitemaps. (Note that on prod/test, the cron job runs daily, but the sitemap gem itself is configured to update the sitemap only monthly.) 

Not sure why the task works when run manually but (at least initially) when run as a cron job on prod/test. 

To test further: change the frequency on test to daily to see if subsequent updates are made by the task?

**Comment by alepbloyd** [comment]
I'm looking at our options for this, but just want to make sure I'm understanding the issue correctly. 

If we want the sitemap to be generated on start-up, like as a part of the `scholarspace-setup.sh` script - it seems like the main use-case for that would be if we are loading data from backups, otherwise there's nothing to map outside of an empty homepage and catalogue. 

If that's the case, the two main options I can think of are:
1. Add to the documentation a note and instructions in the documentation for manually starting the sitemap regenerate job, which seems like it needs to take place _after_ restoring the backup sql databases and ensuring all containers are healthy. Whoever is setting it up can make the decision whether to manually trigger it or wait for it to run at the time set in `config/schedule.rb`, since we can still handle the `crontab` configuration in the `scholarspace-setup.sh` script. 
2. Or add code to the `scholarspace-setup.sh` script to handle backup restoration, which I think would mean handling:
  - Checking if there is backup data to restore from
  - if there is backup data:
    - Copying hyrax DB .sql file from host machine to pg-hyrax container
    - Creating hyrax DB from template0 in pg-hyrax container, then loading from copied .sql dump
    - Copying fedora DB .sql file from host machine to pg-fcrepo container
    - Stopping Fedora container, otherwise cannot drop database to restore from backup
    - Creating fedora DB from template0 in pg-fcrepo container, then loading from copied .sql dump
    - Relaunching fedora container.
    - _After_ those are done, then it's possible to trigger the sitemap regenerate job and populate it correctly. 
 
Option 1 seems easier and more in-line with how we recommend handling restoring from backup in the README, but want to make sure I'm not missing the main issue here. Any thoughts? 

Either way, I'll work on making sure it works as expected with the setting the crontab and checking if the first time it runs on schedule generates a sitemap.xml file.
