### ISSUE TITLE
Improve searching by Date Created field

### ISSUE THREAD

**Issue by DaltonAlves** [gwu-libraries/scholarspace-hyrax#474]
- Allow for sorting by date created
    - Sort by: Date (oldest), Date (Newest)
    - Use date created field
        - Not all items will have date created (not a required field)
    - Date Created Facet list

Is this possible within Hyrax? Does it require blacklight search?

**User Stories:
As a department administrator, I want to facet to the relevant GW Unit and sort by date (newest) to identify the newest items (newest = date of creation, NOT date of upload in GWSS)

As a researcher, I want to sort by date (oldest) within a search result.

As a researcher, I want to facet my search by a specific date year.

As a researcher, I want to facet my search by a date range.

**Comment by kilahimm** [comment]
Also need to investigate how date field is indexed, see recent ETD loads and why the count when facetted by date seems low.

**Comment by kerchner** [comment]
As per recent discussion, suggested steps (apologies for any duplication with other tickets):
- pull current values of date_created from production so that we can identify current patterns
- create a mapping (to implement as a function) that takes a free-text date_created value an returns a sortable Date object - perhaps as a non-visible metadata field on the Work, which can then be used for sorting

**Comment by kerchner** [comment]
I had also looked into this a couple of weeks ago and came across this gem, which I thought would work: 
https://github.com/projectblacklight/blacklight_range_limit
