### ISSUE TITLE
When Keywords field is empty, Catalog view renders values below Keywords in the wrong field shifted up by one

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/scholarspace-hyrax#482]
For works where there are no Keyword values, the Catalog view is rendering values starting from Keyword next to the wrong fields.  Two examples in production are:

For example by searching for Biemer:  https://scholarspace.library.gwu.edu/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=Biemer

Note how these two items render within the list:

- https://scholarspace.library.gwu.edu/concern/gw_etds/6m311q29c
- https://scholarspace.library.gwu.edu/concern/gw_etds/m900nv31p

![image](https://github.com/gwu-libraries/scholarspace-hyrax/assets/3451175/12ee3a8c-7a7a-41f5-9fd3-39dfcba18459)

The pattern appears to be where the work has no Keywords.  All values below the Keywords field are off by one.  So the GW Unit value renders in the Keyword spot, Degree value renders in GW Unit, etc.

Metadata values on the work landing page are rendering correctly.

@maxturer do you want to take this?

**Comment by kerchner** [comment]
@maxturer Makes sense, I figured it was something like what you described.

**Comment by maxturer** [comment]
That should fix it!

**Comment by alepbloyd** [comment]
I think we actually just need to rerun the rake task for fixing empty string keywords when we load in new ETDs via the etd loader. That fixed this before, and this looks like that same issue, since these recent uploads shouldn't be displaying "Keyword:" with nothing in it. 

<img width="484" alt="Screen Shot 2024-01-11 at 3 39 51 PM" src="https://github.com/gwu-libraries/scholarspace-hyrax/assets/17027357/b783c276-749e-4b74-ad78-0fefadbd3199">

**Comment by maxturer** [comment]
That's how I thought it was resolved last time, but probably not a bad idea to keep the HTML fix in place in case something like that happens again.

**Comment by alepbloyd** [comment]
Makes sense to me! Either way, we should probable run that to fix the empty keyword display on the front page.

Rake task is: `gwss:delete_null_keywords` for reference.

**Comment by kerchner** [comment]
@alepbloyd I can run the rake task, but is there a different way that the ETD loader should be populating the keywords when empty, so that it wouldn't be necessary to run the rake task?

**Comment by kerchner** [comment]
(and it does sound like we would still want the improved HTML regardless)

**Comment by alepbloyd** [comment]
@kerchner 

@dolsysmith wrote the task, but it looks like rather than an empty string, the `keyword` value should just be an empty array if there are no keywords. I haven't worked with the ETD loader enough to know if that's a quick fix or not though. 

<img width="723" alt="Screen Shot 2024-01-11 at 3 53 48 PM" src="https://github.com/gwu-libraries/scholarspace-hyrax/assets/17027357/3960d385-8625-4f05-b81a-b35bfb57daaf">

**Comment by kerchner** [comment]
Ref #409
